### PR TITLE
Make bar charts animate

### LINKED ISSUE #1019: Bar charts disappear while animating
Hey Plotly, I'm trying to animate a zoom into a bar chart (see http://codepen.io/hellochar/pen/ozEBXr), but it looks like the bar charts disappear when they're being animated? Is that something intentional or something I'm doing wrong?

Also orthogonally, it looks like many of the different layout properties aren't animated smoothly - for instance, `margin`, `width`, `height`, `bargap`, `xaxis.domain` - is this expected? 

Thanks for your time,
Xiaohan

### PR DESCRIPTION
**Pull request by darabos**
Resolves https://github.com/plotly/plotly.js/issues/1019. So far this is just a revival of @rreusser's plotly/plotly.js#1647. Probably with the same TODOs, maybe more. I just moved a bunch of code into `plotOne()` and it works!

### CODE REVIEW

**Comment by etpinard** [comment]
@darabos nice job! All tests are passing. 

I won't have the chance to test all the `barmode` combinations out until `1.42.0` is released, but this is a solid start! 

Here's how the [`animation.json`](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/animation.json) mock with bar traces instead of scatter trace looks:

peek 2018-10-02 18-08

**Comment by darabos** [comment]
I've got an embarrassing question. :blush: How do I switch between the different frames in that test?

**Comment by etpinard** [comment]
> How do I switch between the different frames in that test?

entering `Plotly.animate(gd)` in the console should do it.

You can checkout the jsdoc:

https://github.com/plotly/plotly.js/blob/5cc37e3504cfa4c1cf1bd632a97b66252126d99a/src/plot_api/plot_api.js#L2656-L2682


or https://plot.ly/javascript/animations/ for more info.

**Comment by saebaxp** [comment]
Thanks for the great work guys!
Has this been merged yet?
Can wait to start animating bar charts...

**Comment by darabos** [comment]
> Thanks for the great work guys!
> Has this been merged yet?

No, I still have to fix the issue that's visible in @etpinard's animation and then ask for a review. Sorry, I kind of forgot about this over the holidays, but I'll try to pick it up this week or next.

> Can wait to start animating bar charts...

Right, I really want this too! :heart:

**Comment by darabos** [comment]
Sorry about the delay. I've merged with current `master` (the conflict wasn't too bad thankfully) and I think I've fixed the issue where the new bar was added at the end instead of in the proper place.

plotly js devtools - edited 2

That looks better now! There is a jump at the end after the axis transition, but I also see that with the scatterplot animation.

Do you have ideas for what else to test? Thanks!

**Comment by raulhuelamo** [comment]
This is looking swell, thanks for the good work! I'm using plotly.js for the first time to build some charts, and I was just curious about the state of the animations. I've used your branch to test a simple chart, and just wanted to drop a GIF with an issues I've found: Bars with starting or ending value = 0 are rendered without an animation.
GIF issue

I've done some tests with `barmode: 'stack'`, and apart from the issue mentioned above, it looks great.
GIF barmode stack

Keep up the good work! Looking forward to see this polished and merged into master.

**Comment by darabos** [comment]
> This is looking swell, thanks for the good work! I'm using plotly.js for the first time to build some charts, and I was just curious about the state of the animations. I've used your branch to test a simple chart, and just wanted to drop a GIF with an issues I've found: Bars with starting or ending value = 0 are rendered without an animation.

Thanks! I've committed a simple fix for that. But I'll have to check the full test suite to see if it has any unintended consequences.

> I've done some tests with `barmode: 'stack'`, and apart from the issue mentioned above, it looks great.

Unfortunately your GIFs don't load for me, but thanks for checking! I forgot about stacked charts... I better add a test for that.

I've also added a simple test to see if bars get added/removed correctly. (I've seen some issues with that when trying this change in our production system.) But this test seems completely broken. :sweat: I'll have to debug a bit more.

**Comment by etpinard** [comment]
Thanks for your hard work @darabos !

Unfortunately I probably won't have time to look at this PR in detail in the next couple week. I'll try, but I won't guarantee anything.

**Comment by jklimke** [comment]
Is there any progress with that feature ? currently the brach has conflicts with the current master of plotly.js.

**Comment by darabos** [comment]
> Is there any progress with that feature ? currently the brach has conflicts with the current master of plotly.js.

Sorry I haven't finished it! I've switched to a non-dashboard project at work, so I could only finish this in my free time now. I'll try to fire up some enthusiasm for this in our dashboard team. Hopefully I can find someone to move this forward!

**Comment by etpinard** [comment]
A first version of animatable bar traces got merged in https://github.com/plotly/plotly.js/pull/4180 and is set to be released in plotly.js `v1.50.0`.

Sorry for delay. I hope you'll like this new feature.

**Comment by darabos** [comment]
> A first version of animatable bar traces got merged in [plotly#4180](https://github.com/plotly/plotly.js/pull/4180) and is set to be released in plotly.js `v1.50.0`.

Wow, that's fantastic! 🎉 Thanks!

**Pull request closed without merging**
